### ISSUE TITLE
$/pdf_xcassets/Rakefile:1:in `<top (required)> error

### ISSUE THREAD

**Issue by jsonwang** [dkhamsing/pdf_xcassets#2]
when i run rake install 
show like error 

cannot load such file -- bundler/gem_tasks
/Users/ak/Desktop/pdf_xcassets/Rakefile:1:in `<top (required)>'
(See full trace by running task with --trace)
please help me. THX

**Comment by dkhamsing** [comment]
What version of bundler do you have?
Try to edit Rakefile and add the following at the top: require 'bundler'

**Comment by jsonwang** [comment]
OK  i upate  bundler version  resolve thx. 
I want to add your friends to say about your contact way,
